name: Vauchi
options:
  bundleIdPrefix: app.vauchi
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  Vauchi:
    type: application
    platform: iOS
    sources:
      - path: Vauchi
        excludes:
          - "**/*.xcassets"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.vauchi.ios
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
    info:
      path: Vauchi/Info.plist
      properties:
        CFBundleDisplayName: Vauchi
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Vauchi uses the camera to scan QR codes for contact exchange."

  VauchiTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VauchiTests
    dependencies:
      - target: Vauchi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.vauchi.ios.tests
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES

schemes:
  Vauchi:
    build:
      targets:
        Vauchi: all
        VauchiTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VauchiTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
