// SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! Theme System
//!
//! Provides color theming with popular open-source themes.
//! Supports dark/light modes and WCAG accessibility validation.
//!
//! Feature file: features/theming.feature

use std::sync::RwLock;

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Theme validation errors
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum ThemeError {
    #[error("Invalid hex color: {0}")]
    InvalidHexColor(String),

    #[error("Insufficient contrast ratio: {actual:.2} (required: {required:.2})")]
    InsufficientContrast { actual: f64, required: f64 },

    #[error("Theme not found: {0}")]
    NotFound(String),

    #[error("Invalid theme JSON: {0}")]
    InvalidThemeJson(String),

    #[error("Design asset store lock poisoned")]
    LockPoisoned,
}

/// Theme mode (light or dark)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[non_exhaustive]
pub enum ThemeMode {
    Light,
    Dark,
}

/// Core color definitions for a theme
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ThemeColors {
    #[serde(rename = "bg-primary")]
    pub bg_primary: String,
    #[serde(rename = "bg-secondary")]
    pub bg_secondary: String,
    #[serde(rename = "bg-tertiary")]
    pub bg_tertiary: String,
    #[serde(rename = "text-primary")]
    pub text_primary: String,
    #[serde(rename = "text-secondary")]
    pub text_secondary: String,
    pub accent: String,
    #[serde(rename = "accent-dark")]
    pub accent_dark: String,
    pub success: String,
    pub error: String,
    pub warning: String,
    pub border: String,
    // ADR-038 Amendment 1: known-optional extensions. Option so a theme
    // may omit any (two-tier contract); None falls back at the renderer.
    #[serde(default)]
    pub surface: Option<String>,
    #[serde(rename = "surface-input", default)]
    pub surface_input: Option<String>,
    #[serde(rename = "surface-muted", default)]
    pub surface_muted: Option<String>,
    #[serde(rename = "surface-elevated", default)]
    pub surface_elevated: Option<String>,
    #[serde(rename = "bottombar-bg", default)]
    pub bottombar_bg: Option<String>,
    #[serde(rename = "text-label", default)]
    pub text_label: Option<String>,
    #[serde(rename = "text-muted", default)]
    pub text_muted: Option<String>,
    #[serde(rename = "accent-bright", default)]
    pub accent_bright: Option<String>,
    #[serde(rename = "icon-accent", default)]
    pub icon_accent: Option<String>,
    #[serde(default)]
    pub teal: Option<String>,
    #[serde(rename = "tint-accent", default)]
    pub tint_accent: Option<String>,
    #[serde(rename = "tint-selected", default)]
    pub tint_selected: Option<String>,
    #[serde(rename = "tint-teal", default)]
    pub tint_teal: Option<String>,
    #[serde(rename = "tint-orange", default)]
    pub tint_orange: Option<String>,
    #[serde(rename = "tint-danger", default)]
    pub tint_danger: Option<String>,
    #[serde(rename = "tint-green", default)]
    pub tint_green: Option<String>,
    #[serde(default)]
    pub scrim: Option<String>,
    // ADR-038 Amendment 3 (2026-06-27): v2 inclusive-redesign roles.
    #[serde(rename = "text-on-accent", default)]
    pub text_on_accent: Option<String>,
    #[serde(rename = "focus-ring", default)]
    pub focus_ring: Option<String>,
}

/// Design tokens for consistent cross-platform rendering.
///
/// Provides spacing, typography, border radius, touch target, and
/// motion values that all platform clients use for layout consistency.
/// Source of truth: themes/tokens.json. Default impl generated by themes/scripts/generate.py.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DesignTokens {
    pub spacing: SpacingTokens,
    pub spacing_direction: SpacingDirectionTokens,
    pub typography: TypographyTokens,
    pub border_radius: BorderRadiusTokens,
    pub touch_target: TouchTargetTokens,
    pub motion: MotionTokens,
    // ADR-038 / inclusive v2 (2026-06-27): font families, weight ramp, and
    // focus-ring metrics. #[serde(default)] for back-compat with tokens
    // serialized before these categories existed.
    #[serde(default)]
    pub font_family: FontFamilyTokens,
    #[serde(default)]
    pub font_weight: FontWeightTokens,
    #[serde(default)]
    pub focus: FocusTokens,
}

/// Spacing scale for margins, padding, and gaps.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SpacingTokens {
    pub xs: u16,
    pub sm: u16,
    #[serde(default = "default_spacing_sm_md")]
    pub sm_md: u16,
    pub md: u16,
    pub lg: u16,
    pub xl: u16,
}

fn default_spacing_sm_md() -> u16 {
    12
}

/// Font size tokens for text hierarchy.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TypographyTokens {
    pub title_size: u16,
    pub subtitle_size: u16,
    pub body_size: u16,
    pub caption_size: u16,
    // ADR-038 Amendment 1: 7-step scale. Defaulted for backward-compat
    // with DesignTokens serialized before the expansion.
    #[serde(default = "default_caption_sm")]
    pub caption_sm: u16,
    #[serde(default = "default_title_lg")]
    pub title_lg: u16,
    #[serde(default = "default_display")]
    pub display: u16,
    // ADR-038 / inclusive v2 (2026-06-27): a "medium" size step, per-step
    // line-heights, and the large-text scale (stored as percent so
    // DesignTokens stays Eq). Defaulted for back-compat with tokens
    // serialized before the inclusive redesign.
    #[serde(default = "default_medium_size")]
    pub medium_size: u16,
    #[serde(default = "default_title_line")]
    pub title_line: u16,
    #[serde(default = "default_subtitle_line")]
    pub subtitle_line: u16,
    #[serde(default = "default_medium_line")]
    pub medium_line: u16,
    #[serde(default = "default_body_line")]
    pub body_line: u16,
    #[serde(default = "default_caption_line")]
    pub caption_line: u16,
    #[serde(default = "default_text_scale_percent")]
    pub text_scale_percent: u16,
}

fn default_caption_sm() -> u16 {
    12
}

fn default_title_lg() -> u16 {
    20
}

fn default_display() -> u16 {
    32
}

fn default_medium_size() -> u16 {
    20
}

fn default_title_line() -> u16 {
    30
}

fn default_subtitle_line() -> u16 {
    24
}

fn default_medium_line() -> u16 {
    28
}

fn default_body_line() -> u16 {
    24
}

fn default_caption_line() -> u16 {
    20
}

fn default_text_scale_percent() -> u16 {
    100
}

/// Directional spacing tokens for content and list items.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct SpacingDirectionTokens {
    pub content_start: u16,
    pub content_end: u16,
    pub list_item_start: u16,
    pub list_item_end: u16,
    #[serde(default = "default_list_item_inline")]
    pub list_item_inline_start: u16,
    #[serde(default = "default_list_item_inline")]
    pub list_item_inline_end: u16,
}

fn default_list_item_inline() -> u16 {
    12
}

/// Border radius tokens for rounded corners.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct BorderRadiusTokens {
    pub sm: u16,
    pub md: u16,
    pub md_lg: u16,
    pub lg: u16,
    // ADR-038 / inclusive v2 (2026-06-27): semantic chip/card/sheet scale.
    // Defaulted for back-compat with pre-redesign tokens.
    #[serde(default = "default_radius_chip")]
    pub chip: u16,
    #[serde(default = "default_radius_card")]
    pub card: u16,
    #[serde(default = "default_radius_sheet")]
    pub sheet: u16,
}

fn default_radius_chip() -> u16 {
    12
}

fn default_radius_card() -> u16 {
    20
}

fn default_radius_sheet() -> u16 {
    28
}

/// Touch target size tokens for accessibility.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TouchTargetTokens {
    pub minimum: u16,
}

/// Motion/animation duration tokens in milliseconds.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct MotionTokens {
    pub enter_duration_ms: u16,
    pub exit_duration_ms: u16,
    pub emphasis_duration_ms: u16,
}

/// Font family names (bundled SIL-OFL webfonts; the renderer maps them to
/// platform font handles).
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FontFamilyTokens {
    pub display: String,
    pub body: String,
    pub mono: String,
}

impl Default for FontFamilyTokens {
    fn default() -> Self {
        Self {
            display: "Bricolage Grotesque".to_string(),
            body: "Hanken Grotesk".to_string(),
            mono: "JetBrains Mono".to_string(),
        }
    }
}

/// Font weight ramp.
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FontWeightTokens {
    pub regular: u16,
    pub medium: u16,
    pub semibold: u16,
    pub bold: u16,
    pub extrabold: u16,
}

impl Default for FontWeightTokens {
    fn default() -> Self {
        Self {
            regular: 400,
            medium: 500,
            semibold: 600,
            bold: 700,
            extrabold: 800,
        }
    }
}

/// Focus-visible ring metrics (the ring colour is a Vauchi/Semantic token).
#[cfg_attr(feature = "schema-gen", derive(schemars::JsonSchema))]
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FocusTokens {
    pub ring_width: u16,
    pub ring_offset: u16,
}

impl Default for FocusTokens {
    fn default() -> Self {
        Self {
            ring_width: 3,
            ring_offset: 2,
        }
    }
}

// DesignTokens defaults are parsed at runtime from the bundled tokens.json
// (themes/tokens.json, embedded into OUT_DIR by build.rs) — no generated
// Rust. Source of truth: themes/tokens.json; values validated by
// check-core-contract.py and the default-value tests below (ADR-038
// Amendment 2).
impl Default for DesignTokens {
    fn default() -> Self {
        const TOKENS_JSON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tokens.json"));
        serde_json::from_slice(TOKENS_JSON)
            .expect("bundled tokens.json must parse into DesignTokens")
    }
}

/// A complete theme definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Theme {
    pub id: String,
    pub name: String,
    pub version: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub license: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    pub mode: ThemeMode,
    pub colors: ThemeColors,
    /// Design tokens for layout consistency. Falls back to defaults if absent in JSON.
    #[serde(default)]
    pub tokens: DesignTokens,
}

impl Theme {
    /// Validate theme has sufficient contrast ratios for accessibility.
    /// Uses WCAG 2.0 AA standard (4.5:1 for normal text).
    pub fn validate_accessibility(&self) -> Result<(), ThemeError> {
        let bg = parse_hex(&self.colors.bg_primary)?;
        let text = parse_hex(&self.colors.text_primary)?;

        let ratio = contrast_ratio(bg, text);
        if ratio < 4.5 {
            return Err(ThemeError::InsufficientContrast {
                actual: ratio,
                required: 4.5,
            });
        }

        Ok(())
    }
}

/// Validate a hex color string
pub fn validate_hex_color(color: &str) -> Result<(), ThemeError> {
    parse_hex(color).map(|_| ())
}

/// Parse a hex color string to RGB tuple
fn parse_hex(color: &str) -> Result<(u8, u8, u8), ThemeError> {
    if !color.starts_with('#') || color.len() != 7 {
        return Err(ThemeError::InvalidHexColor(color.to_string()));
    }

    let r = u8::from_str_radix(&color[1..3], 16)
        .map_err(|_| ThemeError::InvalidHexColor(color.to_string()))?;
    let g = u8::from_str_radix(&color[3..5], 16)
        .map_err(|_| ThemeError::InvalidHexColor(color.to_string()))?;
    let b = u8::from_str_radix(&color[5..7], 16)
        .map_err(|_| ThemeError::InvalidHexColor(color.to_string()))?;

    Ok((r, g, b))
}

/// Calculate relative luminance of a color (WCAG formula)
fn relative_luminance(color: (u8, u8, u8)) -> f64 {
    let (r, g, b) = color;

    let r = srgb_to_linear(r as f64 / 255.0);
    let g = srgb_to_linear(g as f64 / 255.0);
    let b = srgb_to_linear(b as f64 / 255.0);

    0.2126 * r + 0.7152 * g + 0.0722 * b
}

/// Convert sRGB to linear RGB
fn srgb_to_linear(c: f64) -> f64 {
    if c <= 0.03928 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

/// Calculate WCAG contrast ratio between two colors
fn contrast_ratio(c1: (u8, u8, u8), c2: (u8, u8, u8)) -> f64 {
    let l1 = relative_luminance(c1);
    let l2 = relative_luminance(c2);
    let (lighter, darker) = if l1 > l2 { (l1, l2) } else { (l2, l1) };
    (lighter + 0.05) / (darker + 0.05)
}

/// Load themes from JSON data (e.g. from themes.json remote content).
///
/// This is the primary way to load themes. The themes.json file in app-files
/// is the source of truth for all platform themes. Core bundles a single
/// fallback theme for first-launch; all others come from this JSON.
pub fn load_themes_from_json(data: &[u8]) -> Result<Vec<Theme>, ThemeError> {
    serde_json::from_slice(data).map_err(|e| ThemeError::InvalidThemeJson(e.to_string()))
}

/// Get the single bundled default theme (fallback for first-launch before
/// any remote themes are downloaded).
pub fn default_theme() -> Theme {
    default_dark()
}

/// Theme catalog baked at compile time from the sibling `themes/` repo
/// (see `build.rs`). Falls back to a vec containing only `default_theme()`
/// if the JSON is empty / malformed (e.g. when the build couldn't find
/// the catalog file and substituted `[]`).
///
/// Used by `app_engine::screens.rs` to populate
/// `SettingsConfig.available_themes` for the Settings dropdown
/// (problem record `2026-05-01-android-humble-ui-deep-retirement`,
/// Phase 2a/A3a).
pub fn bundled_themes() -> Vec<Theme> {
    const THEMES_JSON: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/themes.json"));
    let themes = load_themes_from_json(THEMES_JSON).unwrap_or_default();
    if themes.is_empty() {
        vec![default_theme()]
    } else {
        themes
    }
}

// ============================================================
// Runtime design-asset stores (RwLock, support hot-reload).
// Mirror i18n::LOCALE_STORE. Tokens are GLOBAL (one tokens.json);
// themes are a catalog. Both fall back to the bundled default when
// unloaded, and a poisoned lock falls back to default rather than
// panicking in the render path (ADR-038 Amendment 2 / hot-reload).
// ============================================================

static DESIGN_TOKENS_STORE: RwLock<Option<DesignTokens>> = RwLock::new(None);
static THEME_STORE: RwLock<Option<Vec<Theme>>> = RwLock::new(None);

/// Load or reload the global design tokens from raw `tokens.json` bytes
/// (e.g. an updated tokens.json delivered via the content system). Until
/// called, `active_design_tokens()` returns the bundled default.
pub fn load_design_tokens_from_bytes(data: &[u8]) -> Result<(), ThemeError> {
    let tokens: DesignTokens =
        serde_json::from_slice(data).map_err(|e| ThemeError::InvalidThemeJson(e.to_string()))?;
    let mut lock = DESIGN_TOKENS_STORE
        .write()
        .map_err(|_| ThemeError::LockPoisoned)?;
    *lock = Some(tokens);
    Ok(())
}

/// The active design tokens: the hot-reloaded set if loaded, else the
/// bundled `DesignTokens::default()`. Read-clone-release — never holds the
/// lock across a render; a poisoned lock falls back to the default.
pub fn active_design_tokens() -> DesignTokens {
    if let Ok(lock) = DESIGN_TOKENS_STORE.read()
        && let Some(tokens) = lock.as_ref()
    {
        return tokens.clone();
    }
    DesignTokens::default()
}

/// Whether design tokens have been hot-loaded (vs the bundled default).
pub fn design_tokens_loaded() -> bool {
    DESIGN_TOKENS_STORE
        .read()
        .map(|lock| lock.is_some())
        .unwrap_or(false)
}

/// Load or reload the theme catalog from raw `themes.json` bytes (parsed
/// via [`load_themes_from_json`]). Until called, [`active_themes`] returns
/// [`bundled_themes`].
pub fn load_themes_from_bytes(data: &[u8]) -> Result<(), ThemeError> {
    let themes = load_themes_from_json(data)?;
    let mut lock = THEME_STORE.write().map_err(|_| ThemeError::LockPoisoned)?;
    *lock = Some(themes);
    Ok(())
}

/// The active theme catalog: the hot-reloaded set if loaded (and
/// non-empty), else [`bundled_themes`].
pub fn active_themes() -> Vec<Theme> {
    if let Ok(lock) = THEME_STORE.read()
        && let Some(themes) = lock.as_ref()
        && !themes.is_empty()
    {
        return themes.clone();
    }
    bundled_themes()
}

fn default_dark() -> Theme {
    Theme {
        id: "catppuccin-mocha".to_string(),
        name: "Catppuccin Mocha".to_string(),
        version: "1.0.0".to_string(),
        author: Some("Catppuccin".to_string()),
        license: Some("MIT".to_string()),
        source: Some("https://github.com/catppuccin/catppuccin".to_string()),
        mode: ThemeMode::Dark,
        colors: ThemeColors {
            bg_primary: "#1e1e2e".to_string(),
            bg_secondary: "#181825".to_string(),
            bg_tertiary: "#313244".to_string(),
            text_primary: "#cdd6f4".to_string(),
            text_secondary: "#a6adc8".to_string(),
            accent: "#89b4fa".to_string(),
            accent_dark: "#74c7ec".to_string(),
            success: "#a6e3a1".to_string(),
            error: "#f38ba8".to_string(),
            warning: "#fab387".to_string(),
            border: "#45475a".to_string(),
            ..Default::default()
        },
        tokens: DesignTokens::default(),
    }
}

// INLINE_TEST_REQUIRED: contract test needs access to load_themes_from_json and internal parsing
#[cfg(test)]
#[path = "theme_tests.rs"]
mod tests;
